{{- if .Values.appSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appSecrets.name | default "app-secrets" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.appSecrets.stringData }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}


