replicaCount: 1

autoscaling:
  enabled: false

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

appConfig:
  enabled: true
  name: app-config
  data:
    NODE_ENV: "development"
    LOG_CHANNEL: "stderr"
    LOG_LEVEL: "debug"
    APP_DEBUG: "true"
    DB_CONNECTION: "pgsql"
    DB_HOST: "tradebytes-postgres.backend-dev.svc.cluster.local"
    DB_PORT: "5432"
    DB_DATABASE: "backend_dev"
    DB_SSL_MODE: "prefer"

    OTEL_ENABLED: "true"
    OTEL_SERVICE_NAME: "laravel-backend-dev"
    OTEL_SERVICE_VERSION: "1.0.0"
    OTEL_SERVICE_NAMESPACE: "development"
    OTEL_ENVIRONMENT: "development"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://opentelemetry-collector.monitoring.svc.cluster.local:4318"
    OTEL_EXPORTER_OTLP_PROTOCOL: "http/protobuf"
    OTEL_TRACES_ENABLED: "true"
    OTEL_TRACES_SAMPLER: "always_on"
    OTEL_TRACES_SAMPLER_ARG: "1.0"
    OTEL_METRICS_ENABLED: "true"
    OTEL_LOGS_ENABLED: "true"
    OTEL_PROPAGATORS: "tracecontext,baggage"

appSecrets:
  enabled: true
  name: app-secrets
  stringData:
    APP_KEY: "base64:qLnGVkERzZS43UZNGJcyUwKcwH/ch2aF/cGG56OHfgg="
    JWT_SECRET: "change-me"

ingress:
  enabled: true
  className: "alb"
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/healthcheck-path: /up
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "30"
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "5"
    alb.ingress.kubernetes.io/healthy-threshold-count: "2"
    alb.ingress.kubernetes.io/unhealthy-threshold-count: "3"
  hosts:
    - host: dev-backend.test
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
